src/Entity/Agencia.php
<?php

namespace App\Entity;

use App\Repository\AgenciaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AgenciaRepository::class)]
class Agencia
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nome = null;

    #[ORM\ManyToOne(inversedBy: 'agencias')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Banco $banco = null;

    #[ORM\OneToOne(mappedBy: 'agencia', cascade: ['persist', 'remove'])]
    private ?Gerente $gerente = null;

    #[ORM\ManyToOne(inversedBy: 'agencyCreator')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $createdByUser = null;

    #[ORM\OneToMany(mappedBy: 'agencia', targetEntity: Conta::class, orphanRemoval: true)]
    private Collection $contas;

    public function __construct()
    {
        $this->contas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(?string $nome): self
    {
        $this->nome = $nome;

        return $this;
    }

    public function getBanco(): ?Banco
    {
        return $this->banco;
    }

    public function setBanco(?Banco $banco): self
    {
        $this->banco = $banco;

        return $this;
    }

    public function getGerente(): ?Gerente
    {
        return $this->gerente;
    }

    public function setGerente(Gerente $gerente): self
    {
        // set the owning side of the relation if necessary
        if ($gerente->getAgencia() !== $this) {
            $gerente->setAgencia($this);
        }

        $this->gerente = $gerente;

        return $this;
    }

    public function getCreatedByUser(): ?User
    {
        return $this->createdByUser;
    }

    public function setCreatedByUser(?User $createdByUser): self
    {
        $this->createdByUser = $createdByUser;

        return $this;
    }

    /**
     * @return Collection<int, Conta>
     */
    public function getContas(): Collection
    {
        return $this->contas;
    }

    public function addConta(Conta $conta): self
    {
        if (!$this->contas->contains($conta)) {
            $this->contas->add($conta);
            $conta->setAgencia($this);
        }

        return $this;
    }

    public function removeConta(Conta $conta): self
    {
        if ($this->contas->removeElement($conta)) {
            // set the owning side to null (unless already changed)
            if ($conta->getAgencia() === $this) {
                $conta->setAgencia(null);
            }
        }

        return $this;
    }

}

src/Form/AgenciaType.php
<?php

namespace App\Form;

use App\Entity\Agencia;
use App\Repository\BancoRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgenciaType extends AbstractType
{
    private $bancos;

    public function __construct(BancoRepository $bancoRepository)
    {
        // $this->bancos = $bancoRepository->findAll();
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nome')
            // ->add('banco', ChoiceType::class, ['choices' => $this->bancos]);
            // ->add('created_at')
            // ->add('updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Agencia::class,
        ]);
    }
}

src/Controller/AgenciaController.php
<?php

namespace App\Controller;

use App\Entity\Agencia;
use App\Entity\Banco;
use App\Form\AgenciaType;
use App\Repository\AgenciaRepository;
use App\Repository\BancoRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/agencia')]
#[IsGranted('IS_AUTHENTICATED_FULLY')]
// #[IsGranted('ROLE_ADMIN_AGENCIA')]
class AgenciaController extends AbstractController
{
    #[Route('/', name: 'app_agencia_index', methods: ['GET'])]
    public function index(AgenciaRepository $agenciaRepository): Response
    {
        return $this->render('agencia/index.html.twig', [
            'agencias' => $agenciaRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_ADMIN_BANCO')]
    #[Route('/new', name: 'app_agencia_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AgenciaRepository $agenciaRepository, BancoRepository $bancoRepository): Response
    {
        $bancos = $bancoRepository->findAll();
        dump($bancos);
        
        $agencia = new Agencia();
        $form = $this->createForm(AgenciaType::class, $agencia);

        $form->add('banco', ChoiceType::class, [
            'choices'=> $bancos,
            'choice_label' => function (?Banco $banco) {
                return $banco ? strtoupper($banco->getNome()) : '';
            }, 
        ]);
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agencia->setCreatedAt(new \Datetime());
            $agencia->setCreatedByUser($this->getUser());
            $agenciaRepository->save($agencia, true);

            return $this->redirectToRoute('app_agencia_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('agencia/new.html.twig', [
            'agencia' => $agencia,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/{id}', name: 'app_agencia_show', methods: ['GET'])]
    public function show(Agencia $agencia): Response
    {
        return $this->render('agencia/show.html.twig', [
            'agencia' => $agencia,
        ]);
    }

    #[IsGranted('ROLE_ADMIN_BANCO')]
    #[Route('/{id}/edit', name: 'app_agencia_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Agencia $agencia, AgenciaRepository $agenciaRepository): Response
    {
        $form = $this->createForm(AgenciaType::class, $agencia);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agencia->setUpdatedAt(new \Datetime());
            $agenciaRepository->save($agencia, true);

            return $this->redirectToRoute('app_agencia_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('agencia/edit.html.twig', [
            'agencia' => $agencia,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_ADMIN_BANCO')]
    #[Route('/{id}', name: 'app_agencia_delete', methods: ['POST'])]
    public function delete(Request $request, Agencia $agencia, AgenciaRepository $agenciaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agencia->getId(), $request->request->get('_token'))) {
            $agenciaRepository->remove($agencia, true);
        }

        return $this->redirectToRoute('app_agencia_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/agencia/_delete_form.html.twig
<form method="post" action="{{ path('app_agencia_delete', {'id': agencia.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agencia.id) }}">
    <button class="btn">Delete</button>
</form>

templates/agencia/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-outline-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/agencia/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Agencia{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Edit Agencia</h1>

        {{ include('agencia/_form.html.twig', {'button_label': 'Update'}) }}

        <a class="btn btn-sm btn-outline-secondary" href="{{ path('app_agencia_index') }}">back to list</a>

        {{ include('agencia/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/agencia/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agencia index{% endblock %}

{% block body %}
    
    <div class="example-wrapper">
        <div class="d-flex justify-content-between align-items-center">
            <h1>Agencia index</h1>
            {% if is_granted('ROLE_ADMIN_BANCO') %}
                <a href="{{ path('app_agencia_new') }}" class="btn btn-sm btn-primary">Create new</a>
            {% endif %}
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Banco</th>
                    <th>Created_at</th>
                    <th>Updated_at</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for agencia in agencias %}
                <tr>
                    <td>{{ agencia.id }}</td>
                    <td>{{ agencia.nome }}</td>
                    <td>{{ agencia.banco.nome }}</td>
                    <td>{{ agencia.createdAt ? agencia.createdAt|date('d/m/Y') : '' }}</td>
                    <td>{{ agencia.updatedAt ? agencia.updatedAt|date('d/m/Y') : '' }}</td>
                    <td>
                        <a class="btn btn-sm btn-outline-primary" href="{{ path('app_agencia_show', {'id': agencia.id}) }}">show</a>
                        <a class="btn btn-sm btn-outline-info" href="{{ path('app_agencia_edit', {'id': agencia.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

templates/agencia/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Agencia{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Create new Agencia</h1>
        
        {{ include('agencia/_form.html.twig') }}
        
        <a class="btn btn-sm btn-outline-secondary" href="{{ path('app_agencia_index') }}">back to list</a>
    </div>
{% endblock %}

templates/agencia/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agencia{% endblock %}

{% block body %}
    <div class="example-wrapper">

        <h1>Agencia</h1>

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ agencia.id }}</td>
                </tr>
                <tr>
                    <th>Nome</th>
                    <td>{{ agencia.nome }}</td>
                </tr>
                <tr>
                    <th>Banco</th>
                    <td>{{ agencia.banco.nome }}</td>
                </tr>
                <tr>
                    <th>Created_at</th>
                    <td>{{ agencia.createdAt ? agencia.createdAt|date('d/m/Y') : '' }}</td>
                </tr>
                <tr>
                    <th>Updated_at</th>
                    <td>{{ agencia.updatedAt ? agencia.updatedAt|date('d/m/Y') : '' }}</td>
                </tr>
            </tbody>
        </table>

        <a class="btn btn-sm btn-outline-secondary" href="{{ path('app_agencia_index') }}">back to list</a>

        <a class="btn btn-sm btn-outline-primary" href="{{ path('app_agencia_edit', {'id': agencia.id}) }}">edit</a>

        {{ include('agencia/_delete_form.html.twig') }}
    </div>
{% endblock %}